### ISSUE TITLE
Accessing nested variables

### ISSUE THREAD

**Issue by sonomirco** [jbutcher5/read-yaml#70]
Hi there, 
This is my yaml file
![image](https://user-images.githubusercontent.com/57708659/192907258-67d79507-c0eb-4ce1-be6c-d57760a18df7.png)

if I pass the value `Dyn.Module` is not able to retrieve the value.
Any suggestions?

**Comment by jbutcher5** [comment]
You should be using ["Dyn", "Module"] to access nested values
